### PR TITLE
added info to templates to the servers

### PR DESCRIPTION
**Pull request by Ledoux**
@franblas 
tx

### CODE REVIEW

**Comment by franblas** [comment]
@Ledoux Can you explain what this is about please 🙏 ?

**Comment by franblas** [comment]
@Ledoux Tests are not passing, please check ;)

**Comment by Ledoux** [comment]
This PR helps then to make default page for the servers displaying some info on the used templates
capture d ecran 2017-02-02 a 14 53 21

**Review by franblas — APPROVED** [review]
@Ledoux Great Thanks! :)

**Comment by pocketjoso** [comment]
Looks cool!

**Pull request merged**
